name: build-web-template

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: 4.6-stable
          path: godot

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.6

      - run: pip install scons

      - run: emcc --version

      - name: Compile web template
        working-directory: godot
        run: |
          scons platform=web target=template_release optimize=size lto=full \
            build_profile=../godot_4_6_2D.gdbuild \
            disable_3d=yes \
            threads=no \
            module_text_server_adv_enabled=no module_text_server_fb_enabled=yes \
            module_websocket_enabled=no module_webrtc_enabled=no \
            module_enet_enabled=no module_upnp_enabled=no \
            module_theora_enabled=no module_webxr_enabled=no \
            module_gridmap_enabled=no module_navigation_enabled=no \
            module_mobile_vr_enabled=no

      - uses: actions/upload-artifact@v4
        with:
          name: thc_web_release_template
          path: godot/bin/godot.web.template_release.wasm32.zip
          retention-days: 90
